//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ac")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub pwd: String,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::msg::Entity")]
    Msg,
    #[sea_orm(has_many = "super::req::Entity")]
    Req,
}

impl Related<super::msg::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Msg.def()
    }
}

impl Related<super::req::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Req.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
