//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "msg")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub ack: i64,
    pub id: i64,
    pub event_type: String,
    pub data: Json,
    pub happened_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ac::Entity",
        from = "Column::Id",
        to = "super::ac::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Ac,
}

impl Related<super::ac::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Ac.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
