//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "rec")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub ack: i64,
    pub code: String,
    pub buyer_id: i64,
    pub seller_id: i64,
    #[sea_orm(column_type = "Decimal(Some((1000, 2)))")]
    pub price: Decimal,
    pub quantity: i64,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ac::Entity",
        from = "Column::BuyerId",
        to = "super::ac::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Ac2,
    #[sea_orm(
        belongs_to = "super::ac::Entity",
        from = "Column::SellerId",
        to = "super::ac::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Ac1,
    #[sea_orm(
        belongs_to = "super::security::Entity",
        from = "Column::Code",
        to = "super::security::Column::Code",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Security,
}

impl Related<super::security::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Security.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
