//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, Copy)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "dir")]
pub enum Dir {
    #[sea_orm(string_value = "Buy")]
    Buy,
    #[sea_orm(string_value = "Sell")]
    Sell,
}
